chore(deps): update rust crates (#88)
This PR contains the following updates:

| Package | Type | Update | Change |
|---|---|---|---|
| [napi](https://redirect.github.com/napi-rs/napi-rs) | dependencies |
patch | `=3.8.0` → `=3.8.1` |
| [reqwest](https://redirect.github.com/seanmonstar/reqwest) |
workspace.dependencies | minor | `=0.12.28` → `=0.13.1` |
| [tokio](https://tokio.rs)
([source](https://redirect.github.com/tokio-rs/tokio)) |
workspace.dependencies | minor | `1.48.0` → `1.49.0` |
| [url](https://redirect.github.com/servo/rust-url) | dependencies |
patch | `=2.5.7` → `=2.5.8` |

---

### Release Notes

<details>
<summary>napi-rs/napi-rs (napi)</summary>

###
[`v3.8.1`](https://redirect.github.com/napi-rs/napi-rs/releases/tag/napi-v3.8.1)

[Compare
Source](https://redirect.github.com/napi-rs/napi-rs/compare/napi-v3.8.0...napi-v3.8.1)

##### Fixed

- *(napi)* wasi debug compile error
([#&#8203;3081](https://redirect.github.com/napi-rs/napi-rs/pull/3081))

</details>

<details>
<summary>seanmonstar/reqwest (reqwest)</summary>

###
[`v0.13.1`](https://redirect.github.com/seanmonstar/reqwest/blob/HEAD/CHANGELOG.md#v0131)

[Compare
Source](https://redirect.github.com/seanmonstar/reqwest/compare/v0.13.0...v0.13.1)

- Fixes compiling with rustls on Android targets.

###
[`v0.13.0`](https://redirect.github.com/seanmonstar/reqwest/blob/HEAD/CHANGELOG.md#v0130)

[Compare
Source](https://redirect.github.com/seanmonstar/reqwest/compare/v0.12.28...v0.13.0)

- **Breaking changes**:
  - `rustls` is now the default TLS backend, instead of `native-tls`.
- `rustls` crypto provider defaults to aws-lc instead of *ring*.
(`rustls-no-provider` exists if you want a different crypto provider)
  - `rustls-tls` has been renamed to `rustls`.
- rustls roots features removed, `rustls-platform-verifier` is used by
default.
    - To use different roots, call `tls_certs_only(your_roots)`.
- `native-tls` now includes ALPN. To disable, use `native-tls-no-alpn`.
  - `query` and `form` are now crate features, disabled by default.
- Long-deprecated methods and crate features have been removed (such as
`trust-dns`, which was renamed `hickory-dns` a while ago).
- Many TLS-related methods renamed to improve autocompletion and
discovery, but previous name left in place with a "soft" deprecation.
(just documented, no warnings)
  - For example, prefer `tls_backend_rustls()` over `use_rustls_tls()`.

#### v0.12.28

- Fix compiling on Windows if TLS and SOCKS features are not enabled.

#### v0.12.27

- Add `ClientBuilder::windows_named_pipe(name)` option that will force
all requests over that Windows Named Piper.

#### v0.12.26

- Fix sending `Accept-Encoding` header only with values configured with
reqwest, regardless of underlying tower-http config.

#### v0.12.25

- Add `Error::is_upgrade()` to determine if the error was from an HTTP
upgrade.
- Fix sending `Proxy-Authorization` if only username is configured.
- Fix sending `Proxy-Authorization` to HTTPS proxies when the target is
HTTP.
- Refactor internal decompression handling to use tower-http.

#### v0.12.24

- Refactor cookie handling to an internal middleware.
- Refactor internal random generator.
- Refactor base64 encoding to reduce a copy.
- Documentation updates.

#### v0.12.23

- Add `ClientBuilder::unix_socket(path)` option that will force all
requests over that Unix Domain Socket.
- Add `ClientBuilder::retry(policy)` and `reqwest::retry::Builder` to
configure automatic retries.
- Add `ClientBuilder::dns_resolver2()` with more ergonomic argument
bounds, allowing more resolver implementations.
- Add `http3_*` options to `blocking::ClientBuilder`.
- Fix default TCP timeout values to enabled and faster.
- Fix SOCKS proxies to default to port 1080
- (wasm) Add cache methods to `RequestBuilder`.

#### v0.12.22

- Fix socks proxies when resolving IPv6 destinations.

#### v0.12.21

- Fix socks proxy to use `socks4a://` instead of `socks4h://`.
- Fix `Error::is_timeout()` to check for hyper and IO timeouts too.
- Fix request `Error` to again include URLs when possible.
- Fix socks connect error to include more context.
- (wasm) implement `Default` for `Body`.

#### v0.12.20

- Add `ClientBuilder::tcp_user_timeout(Duration)` option to set
`TCP_USER_TIMEOUT`.
- Fix proxy headers only using the first matched proxy.
- (wasm) Fix re-adding `Error::is_status()`.

#### v0.12.19

- Fix redirect that changes the method to GET should remove payload
headers.
- Fix redirect to only check the next scheme if the policy action is to
follow.
- (wasm) Fix compilation error if `cookies` feature is enabled (by the
way, it's a noop feature in wasm).

#### v0.12.18

- Fix compilation when `socks` enabled without TLS.

#### v0.12.17

- Fix compilation on macOS.

#### v0.12.16

- Add `ClientBuilder::http3_congestion_bbr()` to enable BBR congestion
control.
- Add `ClientBuilder::http3_send_grease()` to configure whether to send
use QUIC grease.
- Add `ClientBuilder::http3_max_field_section_size()` to configure the
maximum response headers.
- Add `ClientBuilder::tcp_keepalive_interval()` to configure TCP probe
interval.
- Add `ClientBuilder::tcp_keepalive_retries()` to configure TCP probe
count.
- Add `Proxy::headers()` to add extra headers that should be sent to a
proxy.
- Fix `redirect::Policy::limit()` which had an off-by-1 error, allowing
1 more redirect than specified.
- Fix HTTP/3 to support streaming request bodies.
- (wasm) Fix null bodies when calling `Response::bytes_stream()`.

#### v0.12.15

- Fix Windows to support both `ProxyOverride` and `NO_PROXY`.
- Fix http3 to support streaming response bodies.
- Fix http3 dependency from public API misuse.

#### v0.12.14

- Fix missing `fetch_mode_no_cors()`, marking as deprecated when not on
WASM.

#### v0.12.13

- Add `Form::into_reader()` for blocking `multipart` forms.
- Add `Form::into_stream()` for async `multipart` forms.
- Add support for SOCKS4a proxies.
- Fix decoding responses with multiple zstd frames.
- Fix `RequestBuilder::form()` from overwriting a previously set
`Content-Type` header, like the other builder methods.
- Fix cloning of request timeout in `blocking::Request`.
- Fix http3 synchronization of connection creation, reducing unneccesary
extra connections.
- Fix Windows system proxy to use `ProxyOverride` as a `NO_PROXY` value.
- Fix blocking read to correctly reserve and zero read buffer.
- (wasm) Add support for request timeouts.
- (wasm) Fix `Error::is_timeout()` to return true when from a request
timeout.

#### v0.12.12

- (wasm) Fix compilation by not compiler `tokio/time` on WASM.

#### v0.12.11

- Fix decompression returning an error when HTTP/2 ends with an empty
data frame.

#### v0.12.10

- Add `ClientBuilder::connector_layer()` to allow customizing the
connector stack.
- Add `ClientBuilder::http2_max_header_list_size()` option.
- Fix propagating body size hint (`content-length`) information when
wrapping bodies.
- Fix decompression of chunked bodies so the connections can be reused
more often.

#### v0.12.9

- Add `tls::CertificateRevocationLists` support.
- Add crate features to enable webpki roots without selecting a rustls
provider.
- Fix `connection_verbose()` to output read logs.
- Fix `multipart::Part::file()` to automatically include content-length.
- Fix proxy to internally no longer cache system proxy settings.

#### v0.12.8

- Add support for SOCKS4 proxies.
- Add `multipart::Form::file()` method for adding files easily.
- Add `Body::wrap()` to wrap any `http_body::Body` type.
- Fix the pool configuration to use a timer to remove expired
connections.

#### v0.12.7

- Revert adding `impl Service<http::Request<_>>` for `Client`.

#### v0.12.6

- Add support for `danger_accept_invalid_hostnames` for `rustls`.
- Add `impl Service<http::Request<Body>>` for `Client` and `&'_ Client`.
- Add support for `!Sync` bodies in `Body::wrap_stream()`.
- Enable happy eyeballs when `hickory-dns` is used.
- Fix `Proxy` so that `HTTP(S)_PROXY` values take precedence over
`ALL_PROXY`.
- Fix `blocking::RequestBuilder::header()` from unsetting `sensitive` on
passed header values.

#### v0.12.5

- Add `blocking::ClientBuilder::dns_resolver()` method to change DNS
resolver in blocking client.
- Add `http3` feature back, still requiring `reqwest_unstable`.
- Add `rustls-tls-no-provider` Cargo feature to use rustls without a
crypto provider.
- Fix `Accept-Encoding` header combinations.
- Fix http3 resolving IPv6 addresses.
- Internal: upgrade to rustls 0.23.

#### v0.12.4

- Add `zstd` support, enabled with `zstd` Cargo feature.
- Add `ClientBuilder::read_timeout(Duration)`, which applies the
duration for each read operation. The timeout resets after a successful
read.

#### v0.12.3

- Add `FromStr` for `dns::Name`.
- Add `ClientBuilder::built_in_webpki_certs(bool)` to enable them
separately.
- Add `ClientBuilder::built_in_native_certs(bool)` to enable them
separately.
- Fix sending `content-length: 0` for GET requests.
- Fix response body `content_length()` to return value when timeout is
configured.
- Fix `ClientBuilder::resolve()` to use lowercase domain names.

#### v0.12.2

- Fix missing ALPN when connecting to socks5 proxy with rustls.
- Fix TLS version limits with rustls.
- Fix not detected ALPN h2 from server with native-tls.

#### v0.12.1

- Fix `ClientBuilder::interface()` when no TLS is enabled.
- Fix `TlsInfo::peer_certificate()` being truncated with rustls.
- Fix panic if `http2` feature disabled but TLS negotiated h2 in ALPN.
- Fix `Display` for `Error` to not include its source error.

</details>

<details>
<summary>tokio-rs/tokio (tokio)</summary>

###
[`v1.49.0`](https://redirect.github.com/tokio-rs/tokio/releases/tag/tokio-1.49.0):
Tokio v1.49.0

[Compare
Source](https://redirect.github.com/tokio-rs/tokio/compare/tokio-1.48.0...tokio-1.49.0)

### 1.49.0 (January 3rd, 2026)

##### Added

- net: add support for `TCLASS` option on IPv6 ([#&#8203;7781])
- runtime: stabilize `runtime::id::Id` ([#&#8203;7125])
- task: implement `Extend` for `JoinSet` ([#&#8203;7195])
- task: stabilize the `LocalSet::id()` ([#&#8203;7776])

##### Changed

- net: deprecate `{TcpStream,TcpSocket}::set_linger` ([#&#8203;7752])

##### Fixed

- macros: fix the hygiene issue of `join!` and `try_join!`
([#&#8203;7766])
- runtime: revert "replace manual vtable definitions with Wake"
([#&#8203;7699])
- sync: return `TryRecvError::Disconnected` from `Receiver::try_recv`
after `Receiver::close` ([#&#8203;7686])
- task: remove unnecessary trait bounds on the `Debug` implementation
([#&#8203;7720])

##### Unstable

- fs: handle `EINTR` in `fs::write` for io-uring ([#&#8203;7786])
- fs: support io-uring with `tokio::fs::read` ([#&#8203;7696])
- runtime: disable io-uring on `EPERM` ([#&#8203;7724])
- time: add alternative timer for better multicore scalability
([#&#8203;7467])

##### Documented

- docs: fix a typos in `bounded.rs` and `park.rs` ([#&#8203;7817])
- io: add `SyncIoBridge` cross-references to `copy` and `copy_buf`
([#&#8203;7798])
- io: doc that `AsyncWrite` does not inherit from `std::io::Write`
([#&#8203;7705])
- metrics: clarify that `num_alive_tasks` is not strongly consistent
([#&#8203;7614])
- net: clarify the cancellation safety of the `TcpStream::peek`
([#&#8203;7305])
- net: clarify the drop behavior of `unix::OwnedWriteHalf`
([#&#8203;7742])
- net: clarify the platform-dependent backlog in `TcpSocket` docs
([#&#8203;7738])
- runtime: mention `LocalRuntime` in `new_current_thread` docs
([#&#8203;7820])
- sync: add missing period to `mpsc::Sender::try_send` docs
([#&#8203;7721])
- sync: clarify the cancellation safety of `oneshot::Receiver`
([#&#8203;7780])
- sync: improve the docs for the `errors` of mpsc ([#&#8203;7722])
- task: add example for `spawn_local` usage on local runtime
([#&#8203;7689])

[#&#8203;7125]: https://redirect.github.com/tokio-rs/tokio/pull/7125

[#&#8203;7195]: https://redirect.github.com/tokio-rs/tokio/pull/7195

[#&#8203;7305]: https://redirect.github.com/tokio-rs/tokio/pull/7305

[#&#8203;7467]: https://redirect.github.com/tokio-rs/tokio/pull/7467

[#&#8203;7614]: https://redirect.github.com/tokio-rs/tokio/pull/7614

[#&#8203;7686]: https://redirect.github.com/tokio-rs/tokio/pull/7686

[#&#8203;7689]: https://redirect.github.com/tokio-rs/tokio/pull/7689

[#&#8203;7696]: https://redirect.github.com/tokio-rs/tokio/pull/7696

[#&#8203;7699]: https://redirect.github.com/tokio-rs/tokio/pull/7699

[#&#8203;7705]: https://redirect.github.com/tokio-rs/tokio/pull/7705

[#&#8203;7720]: https://redirect.github.com/tokio-rs/tokio/pull/7720

[#&#8203;7721]: https://redirect.github.com/tokio-rs/tokio/pull/7721

[#&#8203;7722]: https://redirect.github.com/tokio-rs/tokio/pull/7722

[#&#8203;7724]: https://redirect.github.com/tokio-rs/tokio/pull/7724

[#&#8203;7738]: https://redirect.github.com/tokio-rs/tokio/pull/7738

[#&#8203;7742]: https://redirect.github.com/tokio-rs/tokio/pull/7742

[#&#8203;7752]: https://redirect.github.com/tokio-rs/tokio/pull/7752

[#&#8203;7766]: https://redirect.github.com/tokio-rs/tokio/pull/7766

[#&#8203;7776]: https://redirect.github.com/tokio-rs/tokio/pull/7776

[#&#8203;7780]: https://redirect.github.com/tokio-rs/tokio/pull/7780

[#&#8203;7781]: https://redirect.github.com/tokio-rs/tokio/pull/7781

[#&#8203;7786]: https://redirect.github.com/tokio-rs/tokio/pull/7786

[#&#8203;7798]: https://redirect.github.com/tokio-rs/tokio/pull/7798

[#&#8203;7817]: https://redirect.github.com/tokio-rs/tokio/pull/7817

[#&#8203;7820]: https://redirect.github.com/tokio-rs/tokio/pull/7820

</details>

<details>
<summary>servo/rust-url (url)</summary>

###
[`v2.5.8`](https://redirect.github.com/servo/rust-url/compare/v2.5.7...v2.5.8)

[Compare
Source](https://redirect.github.com/servo/rust-url/compare/v2.5.7...v2.5.8)

</details>

---

### Configuration

📅 **Schedule**: Branch creation - At any time (no schedule defined),
Automerge - At any time (no schedule defined).

🚦 **Automerge**: Disabled by config. Please merge this manually once you
are satisfied.

♻ **Rebasing**: Whenever PR becomes conflicted, or you tick the
rebase/retry checkbox.

👻 **Immortal**: This PR will be recreated if closed unmerged. Get
[config
help](https://redirect.github.com/renovatebot/renovate/discussions) if
that's undesired.

---

- [ ] <!-- rebase-check -->If you want to rebase/retry this PR, check
this box

---

This PR was generated by [Mend Renovate](https://mend.io/renovate/).
View the [repository job
log](https://developer.mend.io/github/puniyu/nipaw).

<!--renovate-debug:eyJjcmVhdGVkSW5WZXIiOiI0Mi42Ni4xNCIsInVwZGF0ZWRJblZlciI6IjQyLjY5LjEiLCJ0YXJnZXRCcmFuY2giOiJtYWluIiwibGFiZWxzIjpbImRlcGVuZGVuY2llcyJdfQ==-->

---------

Co-authored-by: renovate[bot] <29139614+renovate[bot]@users.noreply.github.com>
Co-authored-by: wuliya <3369906077@qq.com>